// priority: 1000

global.put("unUnified", [
	"actuallyadditions:coal_generator",
	"actuallyadditions:oil_generator",
	"createsifter:advanced_brass_mesh",
	"createsifter:advanced_custom_mesh",
	"createsifter:advanced_sturdy_mesh",
	"createsifter:andesite_mesh",
	"createsifter:brass_mesh",
	"createsifter:brass_sifter",
	"createsifter:custom_mesh",
	"createsifter:string_mesh",
	"createsifter:sturdy_mesh",
	"createsifter:zinc_mesh",
	"easy_villagers:breeder",
	"easy_villagers:converter",
	"easy_villagers:farmer",
	"easy_villagers:incubator",
	"easy_villagers:iron_farm",
	"enderio:block_detector",
	"enderio:soul_engine",
	"ftbstuff:acacia_sluice",
	"ftbstuff:bamboo_sluice",
	"ftbstuff:birch_sluice",
	"ftbstuff:blazing_mesh",
	"ftbstuff:cherry_sluice",
	"ftbstuff:crimson_sluice",
	"ftbstuff:dark_oak_sluice",
	"ftbstuff:diamond_mesh",
	"ftbstuff:diamond_sluice",
	"ftbstuff:gold_mesh",
	"ftbstuff:iron_mesh",
	"ftbstuff:iron_sluice",
	"ftbstuff:jar",
	"ftbstuff:jungle_sluice",
	"ftbstuff:mangrove_sluice",
	"ftbstuff:netherite_sluice",
	"ftbstuff:oak_sluice",
	"ftbstuff:pale_oak_sluice",
	"ftbstuff:spruce_sluice",
	"ftbstuff:warped_sluice",
	"functionalstorage:armory_cabinet",
	"geneticsresequenced:coal_generator",
	"hangglider:glider_framework",
	"hangglider:glider_wing",
	"immersiveengineering:armor_steel_boots",
	"immersiveengineering:armor_steel_chestplate",
	"immersiveengineering:armor_steel_helmet",
	"immersiveengineering:armor_steel_leggings",
	"immersiveengineering:glider",
	"industrialforegoing:marine_fisher",
	"industrialforegoing:pitiful_generator",
	"integrateddynamics:coal_generator",
	"magic_coins:prosperity_amulet",
	"mekanism:creative_chemical_tank",
	"mekanism:creative_fluid_tank",
	"mekanismtools:bronze_boots",
	"mekanismtools:bronze_chestplate",
	"mekanismtools:bronze_helmet",
	"mekanismtools:bronze_leggings",
	"mekanismtools:lapis_lazuli_boots",
	"mekanismtools:lapis_lazuli_chestplate",
	"mekanismtools:lapis_lazuli_helmet",
	"mekanismtools:lapis_lazuli_leggings",
	"mekanismtools:refined_glowstone_boots",
	"mekanismtools:refined_glowstone_chestplate",
	"mekanismtools:refined_glowstone_helmet",
	"mekanismtools:refined_glowstone_leggings",
	"mysticalagriculture:copper_alloy_essence",
	"oritechthings:addon_block_efficient_speed_tier_2",
	"oritechthings:addon_block_efficient_speed_tier_3",
	"oritechthings:addon_block_efficient_speed_tier_4",
	"oritechthings:addon_block_efficient_speed_tier_5",
	"oritechthings:addon_block_efficient_speed_tier_6",
	"oritechthings:addon_block_efficient_speed_tier_7",
	"oritechthings:addon_block_efficient_speed_tier_8",
	"oritechthings:addon_block_efficient_speed_tier_9",
	"pipez:ultimate_upgrade",
	"powah:furnator_basic",
	"powah:furnator_blazing",
	"powah:furnator_hardened",
	"powah:furnator_niotic",
	"powah:furnator_nitro",
	"powah:furnator_spirited",
	"powah:furnator_starter",
	"powah:solar_panel_basic",
	"powah:solar_panel_blazing",
	"powah:solar_panel_hardened",
	"powah:solar_panel_niotic",
	"powah:solar_panel_nitro",
	"powah:solar_panel_spirited",
	"powah:solar_panel_starter",
	"productivebees:honey_generator",
	"reliquary:bat_wing",
	"reliquary:rod_of_lyssa",
	"reliquary:twilight_cloak",
	"rftoolspower:coalgenerator",
	"supplementaries:faucet"
]);

global.put("dyeToGeode", [
	{ dye: "minecraft:orange_dye", geode: "geore:budding_copper" },
	{ dye: "minecraft:red_dye", geode: "geore:budding_redstone" },
	{ dye: "minecraft:brown_dye", geode: "geore:budding_nickel" },
	{ dye: "minecraft:black_dye", geode: "geore:budding_coal" },
	{ dye: "minecraft:yellow_dye", geode: "geore:budding_gold" },
	{ dye: "minecraft:gray_dye", geode: "geore:budding_lead" },
	{ dye: "minecraft:white_dye", geode: "geore:budding_iron" },
	{ dye: "minecraft:light_gray_dye", geode: "geore:budding_tin" },
	{ dye: "minecraft:blue_dye", geode: "geore:budding_lapis" },
	{ dye: "ftbmaterials:ruby_gem", geode: "geore:budding_ruby" },
	{ dye: "ftbmaterials:sapphire_gem", geode: "geore:budding_sapphire" },
	{ dye: "irons_jewelry:topaz", geode: "geore:budding_topaz" }
]);
